PREFIX ex:<http://example.com/> 

CONSTRUCT {
	?uri
		<http://example.com/factor> "Port Ranking";
		<http://example.com/ranking> ?Ranking;
		<http://example.com/city> ?City;
		<http://example.com/country> ?Country.
		
}
WHERE {
	BIND (URI(CONCAT('http://example.com/12/', ?Ranking)) AS ?uri)
}
