PREFIX ex:<http://example.com/> 

CONSTRUCT {
	?uri
		<http://example.com/factor> "EU University Ranking (Business & Management)";
		<http://example.com/ranking> ?Ranking;
		<http://example.com/university> ?University;
		<http://example.com/country> ?Country.
		
}
WHERE {
	BIND (URI(CONCAT('http://example.com/6/', ?Ranking)) AS ?uri)
}